version: '3'

services:
   web:
      image: acerbi1975/clayton-app
      ports:
         - "8080:8080"
      restart: always


   nginx:
      image: nginx:alpine
      ports:
         - "80:80"
      depends_on:
         - web

